[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "encoding"
    version = "@project.version@"
    path = "../encoding-native/build/libs/encoding-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["encoding"]
