[package]
org = "ballerina"
name = "url"
version = "2.2.0"
authors = ["Ballerina"]
keywords = ["url encoding", "url decoding"]
repository = "https://github.com/ballerina-platform/module-ballerina-url"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.1"

[[platform.java11.dependency]]
path = "../native/build/libs/url-native-2.2.0.jar"
